### ISSUE TITLE
老哥你好，我看你是输入法的专家，想请教下，我想了解下fcitx的配置如何配置

### ISSUE THREAD

**Issue by Huangyong657** [yueduz/rime-cqyx-config#1]
老哥你好，我看你是输入法的专家，想请教下
我使用的是fcitx4，在debian11系统上。我没有使用fcitx的ui界面进行配置，而是使用的是qt的qdbus发送命令给fcitx，进行设置和写入。我下载了fcitx-pinyin和英文，我启动我的系统，默认输入法为pinyin，我想改为默认输入法为英文，我如何设置（修改哪个文件），我指的是我重启系统，默认系统输入法为英文。
我的微信hy17857134653，如知晓能否不吝赐教，感谢

**Comment by yueduz** [comment]
你为什么不使用ui配置

**Comment by Huangyong657** [comment]
就是因为，我们做了一个ui，通过dbus方式调用了fcitx5.而且系统不够大，想节省点空间

2024-10-07 00:46:21 "yueduz" ***@***.***> 写道：

你为什么不使用ui配置

**Comment by yueduz** [comment]
你不装ui配置工具，在托盘上点配置会自动打开配文件的啊

**Comment by yueduz** [comment]
![截图 2024-10-25 08-46-08](https://github.com/user-attachments/assets/dcb96dad-c9eb-42af-9eaa-aa5c76b6a94a)
41行就是默认英文
